"""add_stock_analysis_tables

Revision ID: ae8defec933a
Revises: 7f6f2f5a2d11
Create Date: 2026-05-28 23:31:40.510159

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ae8defec933a'
down_revision: Union[str, Sequence[str], None] = '7f6f2f5a2d11'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historical_scan_results',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('classification', sa.String(), nullable=True),
    sa.Column('price_at_scan', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('scanned_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_historical_scan_results_id'), 'historical_scan_results', ['id'], unique=False)
    op.create_index(op.f('ix_historical_scan_results_ticker'), 'historical_scan_results', ['ticker'], unique=False)
    op.create_table('momentum_scores',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('overall_score', sa.Integer(), nullable=True),
    sa.Column('support_score', sa.Integer(), nullable=True),
    sa.Column('ema_score', sa.Integer(), nullable=True),
    sa.Column('sma_score', sa.Integer(), nullable=True),
    sa.Column('rs_score', sa.Integer(), nullable=True),
    sa.Column('vol_score', sa.Integer(), nullable=True),
    sa.Column('macd_score', sa.Integer(), nullable=True),
    sa.Column('scored_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_momentum_scores_id'), 'momentum_scores', ['id'], unique=False)
    op.create_index(op.f('ix_momentum_scores_ticker'), 'momentum_scores', ['ticker'], unique=False)
    op.create_table('stock_signals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('company_name', sa.String(), nullable=True),
    sa.Column('current_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('signal_type', sa.String(), nullable=True),
    sa.Column('score', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('suggested_entry', sa.String(), nullable=True),
    sa.Column('suggested_stop_loss', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('suggested_target', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stock_signals_id'), 'stock_signals', ['id'], unique=False)
    op.create_index(op.f('ix_stock_signals_ticker'), 'stock_signals', ['ticker'], unique=False)
    op.create_table('support_resistance_levels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('support_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('resistance_price', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('is_breakout', sa.Boolean(), nullable=True),
    sa.Column('detected_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_support_resistance_levels_id'), 'support_resistance_levels', ['id'], unique=False)
    op.create_index(op.f('ix_support_resistance_levels_ticker'), 'support_resistance_levels', ['ticker'], unique=False)
    op.create_table('technical_indicators',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(), nullable=False),
    sa.Column('rsi', sa.Float(), nullable=True),
    sa.Column('macd_val', sa.Float(), nullable=True),
    sa.Column('macd_signal', sa.Float(), nullable=True),
    sa.Column('ema10', sa.Float(), nullable=True),
    sa.Column('ema20', sa.Float(), nullable=True),
    sa.Column('sma50', sa.Float(), nullable=True),
    sa.Column('sma200', sa.Float(), nullable=True),
    sa.Column('relative_strength', sa.Float(), nullable=True),
    sa.Column('volume_ratio', sa.Float(), nullable=True),
    sa.Column('calculated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_technical_indicators_id'), 'technical_indicators', ['id'], unique=False)
    op.create_index(op.f('ix_technical_indicators_ticker'), 'technical_indicators', ['ticker'], unique=False)
    op.drop_constraint(op.f('app_settings_key_key'), 'app_settings', type_='unique')
    op.drop_constraint(op.f('dashboard_state_key_key'), 'dashboard_state', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('dashboard_state_key_key'), 'dashboard_state', ['key'], postgresql_nulls_not_distinct=False)
    op.create_unique_constraint(op.f('app_settings_key_key'), 'app_settings', ['key'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_technical_indicators_ticker'), table_name='technical_indicators')
    op.drop_index(op.f('ix_technical_indicators_id'), table_name='technical_indicators')
    op.drop_table('technical_indicators')
    op.drop_index(op.f('ix_support_resistance_levels_ticker'), table_name='support_resistance_levels')
    op.drop_index(op.f('ix_support_resistance_levels_id'), table_name='support_resistance_levels')
    op.drop_table('support_resistance_levels')
    op.drop_index(op.f('ix_stock_signals_ticker'), table_name='stock_signals')
    op.drop_index(op.f('ix_stock_signals_id'), table_name='stock_signals')
    op.drop_table('stock_signals')
    op.drop_index(op.f('ix_momentum_scores_ticker'), table_name='momentum_scores')
    op.drop_index(op.f('ix_momentum_scores_id'), table_name='momentum_scores')
    op.drop_table('momentum_scores')
    op.drop_index(op.f('ix_historical_scan_results_ticker'), table_name='historical_scan_results')
    op.drop_index(op.f('ix_historical_scan_results_id'), table_name='historical_scan_results')
    op.drop_table('historical_scan_results')
    # ### end Alembic commands ###
